[package]
name = "test"
version = "2.1.1"
description = "Motoko testing library to run tests with mops"
repository = "https://github.com/caffeinelabs/mops-test"
keywords = [ "test", "testing", "unit", "suite", "expect", "matchers", "mops" ]
license = "MIT"

[dependencies]
core = "2.0.0"

[toolchain]
moc = "1.0.0"
wasmtime = "40.0.0"

[requirements]
moc = "1.0.0"